# fly.toml app configuration file generated for hexlet-email-trufanov on 2023-05-26T10:58:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hexlet-email-trufanov"
primary_region = "waw"
console_command = "/rails/bin/rails console"
[deploy]
  release_command = "bin/rails make start"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
