Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false